### Listar todas as tarefas
GET http://localhost:5000/api/tarefas/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/tarefas/cadastrar
Content-Type: application/json

{
    "titulo": "Estudar Node.js"
}

### Alterar status da tarefa
PUT http://localhost:5000/api/tarefas/alterar/7bd77eba-421c-41a7-b97c-270837d70293

### Listar não concluídas
GET http://localhost:5000/api/tarefas/naoconcluidas

### Listar concluídas
GET http://localhost:5000/api/tarefas/concluidas